# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e426b597285096dae41baa9b96b1ed4a3fa2063143104b619d229f9b19bb662751e9706c4e0e99c86bdc91d5d291de9dff57071f06cf1d5cbf65153824b6e9cf
  zabbix_url: <%= ENV["ZABBIX_URL"] %>
  zabbix_user: <%= ENV["ZABBIX_USER"] %>
  zabbix_password: <%= ENV["ZABBIX_PASSWORD"] %>

test:
  secret_key_base: 43d37a3dff61a83f7c932e52d9999ea7a7abd1ef2c3ab9ce90d540f2ad4a891940c0063c5c18450fa792cbc07f063c1c9818e0c6c3f8ca9ae30e0f78aeb6ac0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  zabbix_url: <%= ENV["ZABBIX_URL"] %>
  zabbix_user: <%= ENV["ZABBIX_USER"] %>
  zabbix_password: <%= ENV["ZABBIX_PASSWORD"] %>
